"""Constants used across the Sleepy AI Army project."""

# File Names
TASK_DESCRIPTION_FILE = "task_description.md"
TECH_ARCHITECTURE_FILE = "tech_architecture.md"
TASK_CONTEXT_FILE = "task_context.md"
QUESTIONS_ANSWERS_FILE = "questions-and-answers.md"
TASK_STATUS_FILE = "task_status.md"
CHANGELOG_FILE = "changelog.md"

# Status Strings
STATUS_HUMAN_REVIEW_CONTEXT = "HUMAN_REQUIRED_REVIEW_CONTEXT"
STATUS_AWAITING_QUESTIONS = "AWAITING_QUESTIONS"
STATUS_HUMAN_ANSWER_QUESTIONS = "HUMAN_REQUIRED_ANSWER_QUESTIONS"
STATUS_READY_FOR_PRD = "READY_FOR_PRD"

# Feedback Tags (for Q&A file)
FEEDBACK_START_TAG = "<!-- USER_FEEDBACK_START -->"
FEEDBACK_END_TAG = "<!-- USER_FEEDBACK_END -->"
FEEDBACK_PLACEHOLDER = "USER FEEDBACK REQUIRED"