# Application configuration for PoC7 Orchestrator
# TODO: Remove workspace root path - should bea ble to derive this from python file paths like we do in the Secretary code
# workspace_root_path: "C:\\GithubRepos\\Sleepy-AI-Army\\army-man-small-tweak" 
goal_root_path: "C:\\GithubRepos\\Project-Elder\\projects\\isometric_2d_prototype\\ai-goals\\SmallTweak_001_Document_Function_01"
goal_git_path: "C:\\GithubRepos\\Project-Elder"

# Filenames (relative to paths above or defaults in AppConfig model)
task_description_filename: "task-description.md"
manifest_output_filename: "goal-manifest.md" 
changelog_output_filename: "changelog.md" 

# Logging configuration (filenames relative to goal_root_path/log_subdirectory_name)
log_subdirectory_name: "logs"
overview_log_filename: "overview.log"
detailed_log_filename: "detailed.log"

# Template names
manifest_template_filename: "src\\templates\\goal-manifest.j2"

changelog_aider_model: "gemini/gemini-2.0-flash-exp"

# aider_code_model: "gemini/gemini-2.5-pro-preview-03-25"
aider_code_model: "gemini/gemini-2.0-flash-exp"
aider_summary_model: "gemini-2.0-flash-exp"

gemini_weak_model_name: "gemini-2.0-flash-exp"
