# Configuration for Army Man (Small Tweak)

# Paths - overridden by General if run from the General
root_git_path: "C:\\GithubRepos\\Project-Elder"
mission_folder_path: "ai-missions\\update-comments-shoot_component"

# Filenames (relative to paths above or defaults in AppConfig model)
mission_report_filename: "mission-report.md"
mission_description_filename: "mission-spec.md"

# Logging configuration (filenames relative to goal_root_path/log_subdirectory_name)
log_subdirectory_name: "logs"
overview_log_filename: "overview.log"
detailed_log_filename: "detailed.log"

# Template names
mission_report_template_filename: "mission_report_template.md.j2"

# File paths for code modification node
conventions_file_path: "ai-docs/CONVENTIONS.md" # Path relative to root_git_path
aider_config_file_path: ".aider.sleepy.conf.yml" # Path relative to root_git_path

########################
#     LLM MODELS
########################

# aider_code_model: "gemini/gemini-2.5-pro-preview-06-05"

# For testing AI Army Functionality - Use 2.0 flash exp since it's free
aider_code_model: "gemini/gemini-2.0-flash-exp" 

aider_summary_model: "gemini-2.0-flash-exp"

mission_title_extraction_model: "gemini-2.0-flash-exp"

########################
#  GIT CONFIGURATION
########################

branch_naming:
  default_branch_prefix: "ai-mission/"
  max_branch_name_length: 60 # Max total length of the generated branch name
  max_branch_description_length: 40 # Max length for the descriptive part of the branch name (after type prefix, before hash suffix)
  valid_branch_types:
    - "feature"
    - "fix"
    - "polish"
    - "docs"
    - "refactor"
    - "chore"
  branch_hash_length: 7 # Length of the unique hash suffix
