# Application configuration for PoC7 Orchestrator
workspace_root_path: "C:\\GithubRepos\\Sleepy-AI-Army\\poc-7-langgraph-aider" 
# workspace_root_path: "C:\\GithubRepos\\Sleepy-Dev-Team\\poc-7-langgraph-aider" 
goal_root_path: "C:\\GithubRepo\\Project-Elder\\projects\\isometric_2d_prototype\\ai-goals\\SmallTweak_001_Document_Function_01"
goal_git_path: "C:\\GithubRepo\\Project-Elder"

# Filenames (relative to paths above or defaults in AppConfig model)
task_description_filename: "task-description.md"
manifest_output_filename: "goal-manifest.md" 
changelog_output_filename: "changelog.md" 

# Logging configuration (filenames relative to goal_root_path/log_subdirectory_name)
log_subdirectory_name: "logs"
overview_log_filename: "overview.log"
detailed_log_filename: "detailed.log"

# Template names
manifest_template_filename: "ai-docs\\format-templates\\format-goal-manifest.md" 
changelog_template_filename: "ai-docs\\format-templates\\format-changelog.md" 

changelog_aider_model: "gemini/gemini-2.0-flash-exp"
# goal_manifest_aider_model: "gemini/gemini-2.5-flash-preview-04-17"
goal_manifest_aider_model: "gemini/gemini-2.5-pro-preview-03-25"
