# project path - overridden by General if run from the General
project_git_path: "C:\\GithubRepos\\Project-Elder"

# Filenames (relative to paths above)
backlog_file_name: "BACKLOG.md"

ai_missions_directory_name: "ai-missions" # Renamed from ai_goals_directory_name
mission_spec_filename: "mission-spec.md" # Renamed from task_description_filename and value changed

# Default logging configuration
default_log_directory: "logs"
default_log_filename: "backlog-to-missions.log" # Renamed from backlog-to-goals.log

# File to write new mission folders to - Used by general to know which missions to work on
new_mission_folders_filename: "new-mission-folders.txt" 

# Whether to delete the backlog file after all of the missions have been created
# If false, will replace the backlog with a template
delete_backlog_file_on_completion: false

########################
#     LLM MODELS
########################
default_llm_model_name: "gemini-2.0-flash-exp"
